### PR TITLE
feat: support extending cva with custom cx

### PR DESCRIPTION
**Pull request by linden-dg**
### Description

As per discussion #100 this exports a `config` function from cva to allow replacing the default `cx` wrapper with a custom one. The `cva` function now extends/calls the `config` function with the default `clsx`

### Additional context

This is useful as it allow you to extend the default functionality with e.g. [Tailwind Merge](https://github.com/dcastil/tailwind-merge):

```ts
import { config, cx, type CxOptions } from "cva";
import { twMerge } from "tailwind-merge";

export const cva = config({
  cx: (...inputs: CxOptions) => twMerge(cx(inputs)),
});
```

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [X] New Feature
- [X] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/joe-bell/cva/blob/main/CONTRIBUTING.md).
- [X] Follow the [Style Guide](https://github.com/joe-bell/cva/blob/main/CONTRIBUTING.md#style-guide).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by joe-bell** [comment]
@linden-dg thanks so much for raising a PR!

I'm going to hold off merging this for now but I really like where you're going with this and I think it'll tie in nicely with some API changes I have planned for 1.0

Bear with me – pun unintended – and I'll get back to you 🙏

**Comment by linden-dg** [comment]
No worries, I figured I should have a go at the solution rather than just complain!

Looking forward to the API rewrite!

**Comment by joe-bell** [comment]
Hey @linden-dg! I'm exploring an alternative to this approach (very similar) in #160 – would love to get your feedback 🙏

**Comment by linden-dg** [comment]
All good! #166 looks like it will meet my use-case just fine

**Pull request closed without merging**
