### PR TITLE
fix: export ClassProp interface

### PR DESCRIPTION
**Pull request by essejmclean**
Fixes issue #5

### CODE REVIEW

**Comment by joe-bell** [comment]
Cheers for this @essejmclean!

I must admit I'm a bit baffled by this though; I'm not seeing this behaviour in my local [Remix](https://remix.run) project 🤔 

Before going ahead and merging, I'd like to just give this a quick spin locally to see if I can recreate the issue. I'm not _that_ sure I want to export this type, and I want to make sure I fully understand the issue at hand

**Comment by essejmclean** [comment]
Totally agree with that approach. It baffles me that this solved it so easily and that it was throwing the error to begin with.

**Comment by joe-bell** [comment]
Let's continue this chat in #5 before continuing

**Comment by essejmclean** [comment]
Joe helped me resolve the issue I had, which came down to user error. Library works perfectly :)

**Pull request closed without merging**
