### PR TITLE
docs: remove unnecessary comment in README

### PR DESCRIPTION
**Pull request by williamhzo**
### Description

In the **Examples** section, the *React (with CSS Modules)* example mentions a disclaimer comment that isn't relevant for this example. 

### Additional context

The comment states `// ⚠️ Disclaimer: Use of Tailwind CSS is optional` although example is illustrating CSS modules usage.

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/joe-bell/cva/blob/main/CONTRIBUTING.md).
- [x] Follow the [Style Guide](https://github.com/joe-bell/cva/blob/main/CONTRIBUTING.md#style-guide).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by williamhzo** [comment]
> Why so? The codeblock below it uses tailwind classnames 🙂

if i'm not mistaken this particular example is only using CSS modules, not Tailwind classes:

```ts
import {
  base,
  primary,
  secondary,
  small,
  medium,
  primaryMedium,
} from "./button.css";
```

**Comment by alii** [comment]
Ah my apologies, I was looking at the wrong part of the readme 😄 
image

**Comment by williamhzo** [comment]
> Ah my apologies, I was looking at the wrong part of the readme 😄 image

no worries, i wasn't able to link more precisely to the particular example :)

**Comment by joe-bell** [comment]
Good spot, cheers @williamhzo!

**Pull request merged**
