### PR TITLE
docs: update vue example to <script setup>

### PR DESCRIPTION
**Pull request by wobsoriano**
### Description

Updates example to `<script setup>`

### Additional context

It's the recommended syntax if using SFC and Composition API and much better TS support!

https://vuejs.org/api/sfc-script-setup.html#script-setup

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/joe-bell/cva/blob/main/CONTRIBUTING.md).
- [x] Follow the [Style Guide](https://github.com/joe-bell/cva/blob/main/CONTRIBUTING.md#style-guide).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by joe-bell** [comment]
Wonderful, thanks @wobsoriano 🙏 

Please could you try committing again with the `pre-commit` hook – looks like this was missed off

**Comment by wobsoriano** [comment]
> Wonderful, thanks @wobsoriano 🙏
> 
> Please could you try committing again with the `pre-commit` hook – looks like this was missed off

Done!

**Comment by joe-bell** [comment]
Thank you!

**Comment by wobsoriano** [comment]
Oh wow, 2 years later we're in the same company!

**Comment by joe-bell** [comment]
@wobsoriano time flies!

**Pull request merged**
